<?php
$innerstring=$_GET['emailid'].'loopcontrol';
if(isset($_POST['show_all']))
{
$loop_counter++;
$_SESSION[$innerstring]='show_all';
if(isset($_POST['previous'])){
if($_SESSION[$innerstringstart]!=1)
{
$_SESSION[$innerstringstart]=$_SESSION[$innerstringstart]-5;
$_SESSION[$innerstringend]=$_SESSION[$innerstringend]-5;}}
if(isset($_POST['show_more'])){
$_SESSION[$innerstringstart]=$_SESSION[$innerstringstart]+5;
$_SESSION[$innerstringend]=$_SESSION[$innerstringend]+5;}
//*=star_first
}
if(isset($_POST['search_result']))
{
$loop_counter++;
if($_POST['type_of_search']=='by name')
{
$_SESSION[$innerstring]='name';
if(isset($_POST['previous'])){
if($_SESSION[$innerstringstart]!=1)
{
$_SESSION[$innerstringstart]=$_SESSION[$innerstringstart]-5;
$_SESSION[$innerstringend]=$_SESSION[$innerstringend]-5;}}
if(isset($_POST['show_more'])){
$_SESSION[$innerstringstart]=$_SESSION[$innerstringstart]+5;
$_SESSION[$innerstringend]=$_SESSION[$innerstringend]+5;}
//*=star_first
}
if($_POST['type_of_search']=='by blood-group')
{
$_SESSION[$innerstring]='bloodgroup';
if(isset($_POST['previous'])){
if($_SESSION[$innerstringstart]!=1)
{
$_SESSION[$innerstringstart]=$_SESSION[$innerstringstart]-5;
$_SESSION[$innerstringend]=$_SESSION[$innerstringend]-5;}}
if(isset($_POST['show_more'])){
$_SESSION[$innerstringstart]=$_SESSION[$innerstringstart]+5;
$_SESSION[$innerstringend]=$_SESSION[$innerstringend]+5;}
//*=star_first
}
if($_POST['type_of_search']=='by city')
{
$_SESSION[$innerstring]='city';
if(isset($_POST['previous'])){
if($_SESSION[$innerstringstart]!=1)
{
$_SESSION[$innerstringstart]=$_SESSION[$innerstringstart]-5;
$_SESSION[$innerstringend]=$_SESSION[$innerstringend]-5;}}
if(isset($_POST['show_more'])){
$_SESSION[$innerstringstart]=$_SESSION[$innerstringstart]+5;
$_SESSION[$innerstringend]=$_SESSION[$innerstringend]+5;}
//*=star_first
}
}
?>