<?php
if((isset($_POST['show_more'])) || (isset($_POST['previous'])))
{
if($_SESSION[$innerstring]=='show_all')
{
$_POST['show_all']='showall';
$innerstringstart=$innerstring.'start';
$innerstringend=$innerstring.'end';
$_SESSION[$innerstringstart]=1;
$_SESSION[$innerstringend]=5;
}
if($_SESSION[$innerstring]=='name')
{
$_POST['search_result']='search';
$search_n=1;$search_bg=0;$search_c=0;
$innerstringstart=$innerstring.'start';
$innerstringend=$innerstring.'end';
$_SESSION[$innerstringstart]=1;
$_SESSION[$innerstringend]=5;
}
if($_SESSION[$innerstring]=='bloodgroup')
{
$_POST['search_result']='search';
$search_n=0;$search_bg=1;$search_c=0;
$innerstringstart=$innerstring.'start';
$innerstringend=$innerstring.'end';
$_SESSION[$innerstringstart]=1;
$_SESSION[$innerstringend]=5;
}
if($_SESSION[$innerstring]=='city')
{
$_POST['search_result']='search';
$search_n=0;$search_bg=0;$search_c=1;
$innerstringstart=$innerstring.'start';
$innerstringend=$innerstring.'end';
$_SESSION[$innerstringstart]=1;
$_SESSION[$innerstringend]=5;
}
}
?>